### ISSUE TITLE
no `state: connected`

### ISSUE THREAD

**Issue by mixmix** [staltz/ssb-conn-hub#1] opened 2019-03-21 09:46 UTC
hey I'm using `ssb-legacy-conn` and when I call `server.status(console.log)` I get an Object back which is mostly sweet : 

```js
{ progress: 
   { indexes: { start: 63823529, current: 65541925, target: 65895501 } },
  sync: 
   { since: 65895501,
     plugins: 
      { last: 65895501,
        keys: 65895501,
        clock: 65895501,
        time: 65895501,
        feed: 65895501,
        contacts2: 65895501 },
     sync: true },
  local: 
   { '@6ilZq3kN0F+dXFHAPjAwMm87JEb/VdB+LC9eIMW3sa0=.ed25519': { address: [Object] } },
  gossip: {} }
```

BUT what I want to know is who I'm connected to. I know I'm connected to this local peer because I'm doing an initialSync from them....   but there's no `state: connected` anywhere.

Previously with `ssb-gossip` I was seeing this data under the `gossip` property.

**Comment by mixmix** [comment] 2019-03-21 09:46
I do have some slightly odd config to try and force local only connections : 

```js 
  config.gossip = Object.assign({}, config.gossip || {}, {
    local: true,
    friends: false,
    seed: false,
    global: false
  })


  config.connections.outgoing.net = config.connections.outgoing.net.map(conf => {
    return Object.assign(conf, { scope: ['device', 'local'] })
  })

  config.connections.incoming.net = config.connections.incoming.net.map(conf => {
    return Object.assign(conf, { scope: ['device', 'local'] })
  })
```

**Comment by mixmix** [comment] 2019-03-21 09:55
The `server.status.hook` is happening in `ssb-legacy-conn`: 
```ts
    server.status.hook(function(fn: Function) {
      const _status = fn();
      _status.gossip = status;
      for (let [address, data] of connDB.entries()) {
        const state = connHub.getState(address); // <<< culprit?
        if (state === 'connected' || data.stateChange! + 3e3 > Date.now()) {
          if (data.key) {
            status[data.key] = simplifyPeerForStatus({...data, state});
          }
        }
      }
      return _status;
    });
```
looks like the `connHub.getState(address)` is incorrectly returning `undefined` for all addresses, but I've not followed the stack deeper with much success (it's late and I'm at Art~hack!)

Anyway, really need this for being able to successfully show who's I'm connected to in `ssb-ahoy` and in patchbay `/network`

**Comment by staltz** [comment] 2019-03-21 13:07
Thanks! Seems like a real bug, `.state` **should** be there. This module should feel exactly like ssb-gossip, that's the idea. I'll look into it. `connHub.getState(address)` returns undefined if that peer is disconnected, but returns the string `'connected'` if it's connected.

**Comment by staltz** [comment] 2019-03-21 14:24
@mixmix Because I can't quite reproduce this, could you try to add a `console.log(address)` before `const state = connHub.getState(address); // <<< culprit?` ?

Basically the address should be a string, not an object, but I suspect maybe you have an object, because of:

```js
local: { 
  '@6ilZq3kN0F+dXFHAPjAwMm87JEb/VdB+LC9eIMW3sa0=.ed25519': { address: [Object] /*⭐❓⭐*/  } 
},
```

**Comment by staltz** [comment] 2021-06-24 09:50
Difficulties to reproduce this in 2 years, so I'm closing this.

**Closed as completed by staltz** 2021-06-24 09:50 UTC
